### ISSUE TITLE
Allow autoscaling min_size to be 1

### ISSUE THREAD

**Issue by dantestopp** [symbiosis-cloud/terraform-provider-symbiosis#12]
When I want to set the autoscaling min size to 1, I get the following error message: 
`expected autoscaling.0.min_size to be at least (2), got 1`

As it's possible to set the autoscaling min size to 1 in the UI, I would expect to be able to set it through terraform as well.

**Comment by thecodeassassin** [comment]
hi @dantestopp

Thank you for bringing this to our attention, this issue will soon be addressed.

**Comment by thecodeassassin** [comment]
This issue has been fixed in release v0.5.2
