### ISSUE TITLE
Feature: Get kubeconfig

### ISSUE THREAD

**Issue by HerHde** [symbiosis-cloud/terraform-provider-symbiosis#14]
Greetings,

I am missing the feature to retrieve the kubeconfig,like for example [Scaleway](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/data-sources/k8s_cluster#config_file) does it.

Specifically I am looking for the whole config file to reuse in my modules. Is there any chance you're implementing it, so I could migrate over with little effort?

**Comment by Styren** [comment]
Hi,

Thank you for the suggestion! We don't export a raw kube-config string but there's no reason why we couldn't support that. Just out of curiosity, is it not possible to substitute the config by using the CA+key instead? If possible would love to hear a bit more about your use-case.

**Comment by HerHde** [comment]
I'm using the kubeconfig for two things: To save it locally on my machine via [local(file)](https://registry.terraform.io/providers/hashicorp/local/latest)
and to hand it over to the [TF module kustomize](https://registry.terraform.io/providers/kbst/kustomization/latest) to get my initial GitOps setup going.

> Just out of curiosity, is it not possible to substitute the config by using the CA+key instead?

I haven't seen any options for that.

Implementing that would be very nice of you, thank you!

**Comment by Styren** [comment]
> I'm using the kubeconfig for two things: To save it locally on my machine via [local(file)](https://registry.terraform.io/providers/hashicorp/local/latest) and to hand it over to the [TF module kustomize](https://registry.terraform.io/providers/kbst/kustomization/latest) to get my initial GitOps setup going.
> 
> > Just out of curiosity, is it not possible to substitute the config by using the CA+key instead?
> 
> I haven't seen any options for that.
> 
> Implementing that would be very nice of you, thank you!

Thank you, that makes a lot of sense. 🙏
