### ISSUE TITLE
Dev: Architecture is hardcoded

### ISSUE THREAD

**Issue by HerHde** [symbiosis-cloud/terraform-provider-symbiosis#17]
https://github.com/symbiosis-cloud/terraform-provider-symbiosis/blob/7ba6a712aba45e34e3486a8b4d6342a8c4950aa7/Makefile#L7

In the Makefile, the architecture is hardcoded to the Mac kernel, which needs manual adaption for running `make install` on other OSs. Since I can't find an easy fix for automatic detection, I'd recommend to write a few words into the README.

**Comment by Styren** [comment]
> https://github.com/symbiosis-cloud/terraform-provider-symbiosis/blob/7ba6a712aba45e34e3486a8b4d6342a8c4950aa7/Makefile#L7
> 
> In the Makefile, the architecture is hardcoded to the Mac kernel, which needs manual adaption for running `make install` on other OSs. Since I can't find an easy fix for automatic detection, I'd recommend to write a few words into the README.

Nice catch! I'll post a PR that sets it dynamically, but only tested on OSX so far. would you mind checking if it works for your kernel?
