### ISSUE TITLE
Feat: add `symbiosis_cluster` data source

### ISSUE THREAD

**Issue by fhke** [symbiosis-cloud/terraform-provider-symbiosis#9]
# Description

Pull request #8 adds a `symbiosis_cluster` data source, describing a symbiosis Kubernetes cluster.

# Why?

This allows users to dynamically read cluster information during terraform runs, which can be used to configure the Kubernetes/Helm/other providers dynamically without needing to refer to a kubeconfig file. This is a common Terraform pattern used with other managed K8s solutions such as EKS.

**Comment by thecodeassassin** [comment]
hi @fhke thank you for your pull request. We will test and review your PR as soon as possible.

**Comment by HerHde** [comment]
Since #8 was merged, this should be done, right?

**Comment by Styren** [comment]
> Since #8 was merged, this should be done, right?

Correct! Thanks
